# SPDX-FileCopyrightText: 2026 yizhaozhang11
# SPDX-License-Identifier: GPL-3.0-only

"""Generate fixed-size math outlines from the bundled, unmodified LM Math font.

Optional authoring tool: pip install fonttools==4.66.1
The resulting glyph outlines retain the GUST Font License.
"""
from pathlib import Path
from math import isqrt
import json
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.boundsPen import BoundsPen

ROOT = Path(__file__).resolve().parent.parent
FONT = TTFont(ROOT / "public/fonts/latinmodern-math.otf")
GLYPHS = FONT.getGlyphSet()
CMAP = FONT.getBestCmap()


def number(value):
    return f"{value:.2f}".rstrip("0").rstrip(".") if value else "0"


def outline(text, x, baseline, horizontal=1, vertical=1):
    pen = SVGPathPen(GLYPHS, ntos=number)
    for character in text:
        name = CMAP[ord(character)]
        GLYPHS[name].draw(TransformPen(pen, (horizontal, 0, 0, -vertical, x, baseline)))
        x += FONT["hmtx"].metrics[name][0] * horizontal
    return pen.getCommands(), x


def root_shape(square):
    factor = isqrt(square)
    while square % (factor * factor):
        factor -= 1
    radicand = square // (factor * factor)
    paths = []
    cursor = 0
    if factor > 1:
        glyph, cursor = outline(str(factor), cursor, 800)
        paths.append(glyph)
        cursor += 35
    # Use the ordinary radical glyph; tall math-layout variants are unnecessary
    # for these single-line integers. The vinculum stays at a fixed thickness.
    glyph, _ = outline("√", cursor, 32.8, .82, .82)
    paths.append(glyph)
    bar_start = cursor + 680
    glyph, end = outline(str(radicand), cursor + 728, 800)
    paths.append(glyph)
    width = end + 38
    bar = f"M{number(bar_start)} 0H{number(end + 26)}V32.8H{number(bar_start)}Z"
    return {"width": width, "height": 860, "path": "".join(paths) + bar}


squares = sorted({x*x + y*y for x in range(9) for y in range(9-x)
                  if isqrt(x*x + y*y) ** 2 != x*x + y*y})
outlines = {square: root_shape(square) for square in squares}
(ROOT / "src/math-outlines.ts").write_text(
    "// Generated by tools/draw-math.py from Latin Modern Math 1.959.\n"
    "// Glyph outlines: GUST Font License; see public/fonts/NOTICE.md.\n"
    "export const mathOutlines: Record<number, { width: number; height: number; path: string }> = "
    + json.dumps(outlines, ensure_ascii=False, separators=(",", ":")) + ";\n", encoding="utf-8")

# Raise the smaller sign by 0.06 of its own em, keeping its lower bar close
# to the upright i's baseline. Fit visible ink rather than advance boxes.
sign_scale = .8
sign_baseline = -.06 * sign_scale * FONT["head"].unitsPerEm
plusminus, next_x = outline("±", 0, sign_baseline, sign_scale, sign_scale)
imaginary, _ = outline("i", next_x, 0)
bounds = BoundsPen(GLYPHS)
for char, x, baseline, scale in [("±", 0, sign_baseline, sign_scale), ("i", next_x, 0, 1)]:
    GLYPHS[CMAP[ord(char)]].draw(TransformPen(bounds, (scale, 0, 0, -scale, x, baseline)))
left, top, right, bottom = bounds.bounds
size = 64
ink_scale = size * .75 / (right - left)
offset_x = size / 2 - (left + right) * ink_scale / 2
offset_y = size / 2 - (top + bottom) * ink_scale / 2
logo = (
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">'
    '<!-- Latin Modern Math outlines; GUST Font License. -->'
    '<rect width="64" height="64" fill="#333"/>'
    f'<path fill="#fff" transform="translate({offset_x:.8f} {offset_y:.8f}) scale({ink_scale:.8f})" '
    f'd="{plusminus}{imaginary}"/></svg>\n'
)
for name in ["brand.svg", "favicon.svg"]:
    (ROOT / "public" / name).write_text(logo, encoding="utf-8")
print(f"Generated {len(outlines)} radicals and two matching logo assets.")
